name: Continuous Integration and Merge Workflow
run-name: Commit ${{ github.sha }} of branch ${{ github.ref}} by @${{ github.actor }}

on:
  push:
    branches:
      - develop
    
permissions:
  contents: write  # Adjust permissions as needed

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile, Unit Test and Install
        id: unit-tests
        run: mvn clean install

      - name: Upload test reports
        if: always() && steps.unit-tests.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: '**/target/surefire-reports/*.xml'

      - name: Integration Test
        id: integration-tests
        run: mvn failsafe:integration-test

      - name: Upload integration test reports
        if: always() && steps.integration-tests.outcome == 'success'
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-reports
          path: '**/target/failsafe-reports/*.xml'

  create-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Compile
        run: mvn clean package -DskipTests

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: dev-pre-release
          release_name: "Release ${{ github.sha }}"
          body: "Automatically generated release from ${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload JAR to GitHub Releases
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: mitroo/target/mitroo-0.1.jar
          asset_name: mitroo-0.1.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
